DEMO_CONTENT = [
    {
        "content_type": "movie",
        "title": "Blade Runner 2049",
        "original_title": "Blade Runner 2049",
        "description": "A quiet, monumental sci-fi noir about memory, identity and loneliness in a synthetic future.",
        "genres": ["sci-fi", "drama", "mystery"],
        "tags": ["cyberpunk", "neo-noir", "androids"],
        "moods": ["cinematic", "dark", "philosophical"],
        "image_url": "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
        "banner_url": "https://image.tmdb.org/t/p/w780/5w8sNlP9I7fS0WItqgJ3l9J52Ui.jpg",
        "release_year": 2017,
        "rating": 8.0,
        "popularity": 96,
        "source": "demo",
        "external_id": "blade-runner-2049",
        "external_url": "https://www.themoviedb.org/movie/335984",
        "language": "en",
    },
    {
        "content_type": "tv",
        "title": "Severance",
        "original_title": "Severance",
        "description": "Office dread, corporate mystery and surreal emotional tension in one immaculate puzzle box.",
        "genres": ["thriller", "sci-fi", "drama"],
        "tags": ["workplace", "mystery", "dystopia"],
        "moods": ["strange", "psychological", "minimal"],
        "image_url": "https://image.tmdb.org/t/p/w500/lFf6LLrQjYldcZItzOkGmMMigP7.jpg",
        "banner_url": "https://image.tmdb.org/t/p/w780/8B7Qv6Gg5fUiWn5JQkS7XlU9W4.jpg",
        "release_year": 2022,
        "rating": 8.7,
        "popularity": 92,
        "source": "demo",
        "external_id": "severance",
        "external_url": "https://www.themoviedb.org/tv/95396",
        "language": "en",
    },
    {
        "content_type": "anime",
        "title": "Death Note",
        "original_title": "Death Note",
        "description": "A brilliant student discovers a deadly notebook and enters a psychological duel with a legendary detective.",
        "genres": ["mystery", "thriller", "supernatural"],
        "tags": ["cat-and-mouse", "antihero", "strategy"],
        "moods": ["dark", "psychological", "tense"],
        "image_url": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-4r88a1tsBEIz.jpg",
        "banner_url": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535.jpg",
        "release_year": 2006,
        "rating": 8.6,
        "popularity": 90,
        "source": "demo",
        "external_id": "death-note",
        "external_url": "https://anilist.co/anime/1535",
        "language": "ja",
    },
    {
        "content_type": "game",
        "title": "Control",
        "original_title": "Control",
        "description": "A brutalist paranormal action game filled with impossible architecture, secrets and eerie power.",
        "genres": ["action", "adventure", "sci-fi"],
        "tags": ["paranormal", "brutalism", "third-person"],
        "moods": ["strange", "cinematic", "mysterious"],
        "image_url": "https://media.rawg.io/media/games/b62/b6254b63fbdcc1f6a43ef417f9d01882.jpg",
        "banner_url": "https://media.rawg.io/media/screenshots/8f1/8f1a03c6fd5e6d4a77df4e587013dc57.jpg",
        "release_year": 2019,
        "rating": 8.2,
        "popularity": 84,
        "source": "demo",
        "external_id": "control",
        "external_url": "https://rawg.io/games/control",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "Project Hail Mary",
        "original_title": "Project Hail Mary",
        "description": "A lone astronaut wakes up far from Earth and has to solve a cosmic survival problem with wit and heart.",
        "genres": ["sci-fi", "adventure"],
        "tags": ["space", "survival", "first-contact"],
        "moods": ["smart", "hopeful", "fast-paced"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa",
        "release_year": 2021,
        "rating": 8.8,
        "popularity": 80,
        "source": "demo",
        "external_id": "project-hail-mary",
        "external_url": "https://openlibrary.org/isbn/9780593135204",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "Dark Matter",
        "original_title": "Dark Matter",
        "description": "A fast sci-fi thriller about identity, alternate lives and the cost of every choice not taken.",
        "genres": ["sci-fi", "thriller"],
        "tags": ["multiverse", "identity", "pace"],
        "moods": ["tense", "mind-bending", "fast-paced"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9781101904220-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1519681393784-d120267933ba",
        "release_year": 2016,
        "rating": 8.2,
        "popularity": 78,
        "source": "demo",
        "external_id": "dark-matter-book",
        "external_url": "https://openlibrary.org/isbn/9781101904220",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "The Silent Patient",
        "original_title": "The Silent Patient",
        "description": "A psychological mystery built around obsession, silence and a final turn designed to reframe everything.",
        "genres": ["thriller", "mystery"],
        "tags": ["psychology", "twist", "crime"],
        "moods": ["dark", "tense", "psychological"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1507842217343-583bb7270b66",
        "release_year": 2019,
        "rating": 8.0,
        "popularity": 76,
        "source": "demo",
        "external_id": "silent-patient",
        "external_url": "https://openlibrary.org/isbn/9781250301697",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "Dune",
        "original_title": "Dune",
        "description": "A vast desert epic about power, prophecy, ecology and political survival on a hostile planet.",
        "genres": ["sci-fi", "fantasy"],
        "tags": ["politics", "desert", "empire"],
        "moods": ["epic", "dense", "cinematic"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
        "release_year": 1965,
        "rating": 8.7,
        "popularity": 90,
        "source": "demo",
        "external_id": "dune",
        "external_url": "https://openlibrary.org/isbn/9780441172719",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "Tomorrow, and Tomorrow, and Tomorrow",
        "original_title": "Tomorrow, and Tomorrow, and Tomorrow",
        "description": "A warm, bittersweet novel about games, creative partnership, ambition and complicated friendship.",
        "genres": ["drama", "literary fiction"],
        "tags": ["games", "friendship", "creativity"],
        "moods": ["emotional", "smart", "melancholy"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9780593321201-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1511512578047-dfb367046420",
        "release_year": 2022,
        "rating": 8.4,
        "popularity": 79,
        "source": "demo",
        "external_id": "tomorrow-and-tomorrow",
        "external_url": "https://openlibrary.org/isbn/9780593321201",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "The Seven Husbands of Evelyn Hugo",
        "original_title": "The Seven Husbands of Evelyn Hugo",
        "description": "A glamorous, emotional Hollywood confession about fame, love, reinvention and hidden truth.",
        "genres": ["drama", "romance"],
        "tags": ["hollywood", "fame", "identity"],
        "moods": ["emotional", "cinematic", "glamorous"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9781501161933-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1485846234645-a62644f84728",
        "release_year": 2017,
        "rating": 8.5,
        "popularity": 84,
        "source": "demo",
        "external_id": "evelyn-hugo",
        "external_url": "https://openlibrary.org/isbn/9781501161933",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "Neuromancer",
        "original_title": "Neuromancer",
        "description": "A cyberpunk classic with hackers, artificial intelligence, neon paranoia and hard-edged future noir.",
        "genres": ["sci-fi", "noir"],
        "tags": ["cyberpunk", "hacker", "ai"],
        "moods": ["dark", "strange", "noir"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1519608487953-e999c86e7455",
        "release_year": 1984,
        "rating": 8.1,
        "popularity": 72,
        "source": "demo",
        "external_id": "neuromancer",
        "external_url": "https://openlibrary.org/isbn/9780441569595",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "The House in the Cerulean Sea",
        "original_title": "The House in the Cerulean Sea",
        "description": "A gentle fantasy about found family, kindness and choosing wonder over fear.",
        "genres": ["fantasy", "romance"],
        "tags": ["found-family", "magic", "comfort"],
        "moods": ["comfort", "hopeful", "warm"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9781250217288-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
        "release_year": 2020,
        "rating": 8.3,
        "popularity": 75,
        "source": "demo",
        "external_id": "cerulean-sea",
        "external_url": "https://openlibrary.org/isbn/9781250217288",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "Gone Girl",
        "original_title": "Gone Girl",
        "description": "A sharp domestic thriller about performance, marriage, manipulation and media spectacle.",
        "genres": ["thriller", "mystery"],
        "tags": ["crime", "marriage", "twist"],
        "moods": ["dark", "cynical", "tense"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
        "release_year": 2012,
        "rating": 8.1,
        "popularity": 82,
        "source": "demo",
        "external_id": "gone-girl",
        "external_url": "https://openlibrary.org/isbn/9780307588371",
        "language": "en",
    },
    {
        "content_type": "book",
        "title": "Circe",
        "original_title": "Circe",
        "description": "A mythic, intimate reinvention about exile, power, transformation and becoming yourself.",
        "genres": ["fantasy", "mythology"],
        "tags": ["greek-myth", "witch", "transformation"],
        "moods": ["lyrical", "emotional", "epic"],
        "image_url": "https://covers.openlibrary.org/b/isbn/9780316556347-L.jpg",
        "banner_url": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
        "release_year": 2018,
        "rating": 8.4,
        "popularity": 77,
        "source": "demo",
        "external_id": "circe",
        "external_url": "https://openlibrary.org/isbn/9780316556347",
        "language": "en",
    },
    {
        "content_type": "podcast",
        "title": "Darknet Diaries",
        "original_title": "Darknet Diaries",
        "description": "Storie vere di hacker, sicurezza, identita digitali e sistemi che si rompono nel modo piu umano possibile.",
        "genres": ["technology", "true crime", "cybersecurity"],
        "tags": ["hackers", "internet", "investigation"],
        "moods": ["dark", "cerebral", "tense"],
        "image_url": "https://i.scdn.co/image/ab6765630000ba8a0c9c2b506f8d2fbe6c75f7a1",
        "banner_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
        "release_year": 2017,
        "rating": 8.8,
        "popularity": 91,
        "source": "demo",
        "external_id": "darknet-diaries",
        "external_url": "https://open.spotify.com/show/4XPl3uEEL9hvqMkoZrzbx5",
        "language": "en",
    },
    {
        "content_type": "podcast",
        "title": "Philosophize This!",
        "original_title": "Philosophize This!",
        "description": "Un percorso accessibile dentro idee enormi: identita, potere, senso, societa e il modo in cui pensiamo.",
        "genres": ["philosophy", "culture", "ideas"],
        "tags": ["meaning", "identity", "thought"],
        "moods": ["cerebral", "reflective", "intimate"],
        "image_url": "https://i.scdn.co/image/ab6765630000ba8a8f1bb8b7f40a7f2a1ff5c5ec",
        "banner_url": "https://images.unsplash.com/photo-1455390582262-044cdead277a",
        "release_year": 2013,
        "rating": 8.6,
        "popularity": 84,
        "source": "demo",
        "external_id": "philosophize-this",
        "external_url": "https://open.spotify.com/show/2Shpxw7dPoxRJCdfFXTWLE",
        "language": "en",
    },
    {
        "content_type": "podcast",
        "title": "The Daily",
        "original_title": "The Daily",
        "description": "Un modo chiaro e narrativo per capire cosa sta succedendo, senza perdersi nel rumore infinito delle news.",
        "genres": ["news", "society", "politics"],
        "tags": ["context", "world", "daily"],
        "moods": ["clear", "focused", "current"],
        "image_url": "https://i.scdn.co/image/ab6765630000ba8a5d2f1f4f7d3fd2f5d6f6c78d",
        "banner_url": "https://images.unsplash.com/photo-1504711434969-e33886168f5c",
        "release_year": 2017,
        "rating": 8.2,
        "popularity": 93,
        "source": "demo",
        "external_id": "the-daily",
        "external_url": "https://open.spotify.com/show/3IM0lmZxpFAY7CwMuv9H4g",
        "language": "en",
    },
]
